config/routes.rb
Rails.application.routes.draw do
  get 'sitio/index'

  root 'sitio#index'

  get 'acerca' => 'sitio#acerca'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sitio_controller.rb
class SitioController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sitio_helper.rb
module SitioHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">RubyTest</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Inicio", root_path%></li>
        <li><%= link_to "Acerca", acerca_path%></li>
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
 		<li><%= link_to "Iniciar Sesion", "#"%></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%=render "layouts/header" %>

<div class="container">
	<%= yield %>

	<%=render "sitio/footer" %>
</div>
</body>
</html>

app/views/sitio/_footer.html.erb
<div class="footer">
	<small>
		Hector Andrade Project
	</small>
</div>

app/views/sitio/acerca.html.erb

<h1>Sitio#acerca</h1>

<p>
	ir a Oja.la
	<%= link_to "Enlace a Oja.la", "http://oja.la"%>
</p>

app/views/sitio/index.html.erb
<div class="jumbotron">
  <h1>Curso Ruby on Rails</h1>
  <p>orem ipsum dolor sit amet, consectetur adipiscing elit.</p>
  <p><%= link_to "Registrarse", "http://oja.la", :class=> "btn btn-primary"%></p>
</div>